### ISSUE TITLE
Cannot find module 'cross-spawn'

### ISSUE THREAD

**Issue by dynamikus** [timoxley/npm-run#18]
npm-run breaks due to "cross-spawn" not being installed. This dependency got removed in the last commit.
``` 
npm-run app-config build -e staging-f ./src/config.default.js
module.js:545
    throw err;
    ^
Error: Cannot find module 'cross-spawn'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-run/index.js:5:13)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

**Comment by timoxley** [comment]
ah, my bad. Fixed in 5.0.1.
